### ISSUE TITLE
Package manager es demasiado distro specific

### ISSUE THREAD

**Issue by JavierCorralLizarraga** [LornartheBreton/linux_workshop#1]
Hay que dar entendimiento holistico de los package manager indistinto de la distro,
o tendras problemas especialmente con los que sigan tu consejo de usar manjaro

**Comment by LornartheBreton** [comment]
Es parte del punto (que sepan updatear, agregar paquetes, upgradear, etc), pero Chuco si nos enfatizó que sea Ubuntu-based.

Aclararé en el siguiente commit.

**Comment by LornartheBreton** [comment]
Ya se updateó el syllabus con temas menos distro-specific.
